### ISSUE TITLE
Wrong directories when extracting the emulator data

### ISSUE THREAD

**Issue by arthurmloureiro** [ivansladoljev/Navigator#1]
Hi, Ivan!
(this is a _GitHub Issue_; people will open them when they find a bug or have a question or suggestion).

I've followed the instructions to download the emulator data from Zenedo and extract them into `src/DATA/` which gives this folder structure here:

<img width="395" alt="Screenshot 2023-10-11 at 15 15 33" src="https://github.com/ivansladoljev/Navigator/assets/6471279/a83f947b-7ff7-4dbe-8159-8e153d8d087b">

When importing the module, Julia looks for the emulator data in `Navigator/src/DATA/chains_weights/weights/` instead of `Navigator/src/DATA/weights/`:
```julia
julia> using Navigator
[ Info: Precompiling Navigator [fa0937c5-fa6c-4797-9484-de2c51beef9b]
ERROR: LoadError: SystemError: opening file "Navigator/src/DATA/chains_weights/weights/weights_cosmopowerspace_10000/weights_TT_lcdm.npy": No such file or directory
```

I'd suggest removing the `chain_weights/` folder from the emulator's path.

Cheers!

**Comment by ivansladoljev** [comment]
You are right. This happens if you download the files through terminal and not manually. I will change this immediately and upgrade the ReadMe file.
